apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/MaherBaccouche/hello-world-gcp.git # If using your own repository, replace this value
