apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-deploy-template
  namespace: tekton-pipelines
spec:
  params:
  - name: buildRevision
    description: The Git commit revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: build-deploy-
    spec:
      taskRef:
        name: build-docker-image-from-git-source
      serviceAccountName: task
      params:
      - name: buildRevision
        value: $(tt.params.buildRevision)
      - name: appGitUrl
        value: 'https://github.com/MaherBaccouche/hello-world-gcp.git'
      - name: appImage
        value: 'maherbaccouche/tektondemo'
          #workspaces:
          #- name: app-source
          #emptyDir: {}
          #- name: config-source
          #emptyDir: {}